### ISSUE TITLE
Login Faied & Transport error

### ISSUE THREAD

**Issue by scotthuang1989** [Microsoft/Cognitive-Speech-STT-Windows#13]
I follow every step to build this app, When I try to use it. It show following error message, I use my key from Bing Speech - Preview. any suggestion what I should try next?

error message: 
--- Start speech recognition using short wav file with ShortPhrase mode in en-US language ----

--- Error received by OnConversationErrorHandler() ---
Error code: LoginFailed
Error text: Transport error

**Comment by scottunderhill** [comment]
I get the same error as well. 
Error: -1910505470

Yeah, I have tried different constructors. Change network, vpn.  But nothing works. 

Very confident that I got the Key right (tried Key 1, Key 2)   still no luck

**Comment by scotthuang1989** [comment]
I tried this application today. It works.
No idea what happped.

**Comment by scottunderhill** [comment]
Same happened with me.

**Comment by ThibautCantet** [comment]
i have the same problem on the android and windows samples

**Comment by hojjatabdollahi** [comment]
I get the same error. But after a number of normal responses.
I need to use "short phrase recognition" and it works for a few times (for example the first 50 times.) then it starts giving me this error.
I am using the code in the example provided for Windows SDK in C#. 
I thought it might be because I'm using the free version. So I purchased it and used the new key. But it still happens. Why?

**Comment by scotthuang1989** [comment]
If you purchased this service, may be you can contact customer service to find out.

**Comment by priyaravi20** [comment]
Hi - Speech API auth endpoint changed on Sep 21. You need to get new keys to hit the new endpoint. Keys obtained before Sep21 will continue to work with the old SDK. Can you confirm if you are using new keys with latest SDK? The error code seems to be an authentication issue.

- Microsoft Speech PM

**Comment by hojjatabdollahi** [comment]
I purchased the service a couple of days ago. Definitely after Sep 21. The service works for almost 10 minutes which means it's not authentication issue, and if I wait for a couple of seconds (like 30 seconds) it will work again.
I contacted them about SpeechClient.dll and they said they are not going to opensource it and they will not provide SpeechClient.pdb, so I don't know how to debug any further and what to do next?

**Comment by github-creatusse** [comment]
I've tested this sample app today and received the same error. This is using Azure Service with Standard Pricing tier. Endpoint:
https://api.cognitive.microsoft.com/sts/v1.0

**Comment by CrimsonArc** [comment]
Same here. I use the REST API to drained all of the 5000 transactions quota, after that, the quota seems to be reset properly at the next month. But, from the new month, every time I try to request recognition using the Windows WPF Example, it always returns LoginFailed. Until now, this problem has been going on for 10 days.

**Comment by scotthuang1989** [comment]
Yes. This is very frustrating.

**Comment by jeffrschneider** [comment]
Getting a login fail.

**Comment by faisalsaghir7** [comment]
getting the same error ... what is solution of it ?

**Comment by kasebe** [comment]
Me too.
It looks like working fine at activity log on Azure portal.

**Comment by leviyakir** [comment]
We switched to the new SpeechClient.dll (1.0.0.2) upgrading from 0.4.10.1 and got login failed with the old key. We generated a new key but it fails as well.
How can we use the new version of this service?

**Comment by moelazha** [comment]
Are you making sure the key you are using is from "Bing Speech - Preview" not other service?
putting a key from a different service will give the same error.

**Comment by leviyakir** [comment]
Later that day it started working.
However, my hopes the new version will be more stable have not been fulfilled. Still crashes quite frequently. I have dumps and logs if anybody has access to the source code.

**Comment by jabels** [comment]
Not the login error but if using remote desktop with remote audio device you may receive the following error:
--- Error received by OnConversationErrorHandler() ---
Error code: -2147467263
Error text: Transport error

Could not resolve using RDP but running under local Visual Studio worked fine.

**Comment by leviyakir** [comment]
Using the 1.0.0.2 nuget we frequently experience crashes as we start using speechclient.dll. Here is the relevant stack trace. Note that the crashing thread is a working thread in SpeechClient.dll.
ExceptionAddressSymbolInfo=C:\Program Files\Screenovate\BluePhone\SpeechClient.dll! DllUnregisterServer - 0x00007FF9F9B86783, module offset(base): 0x46783(0x7ff9f9b40000)
StackTrace00=C:\Program Files\Screenovate\BluePhone\SpeechClient.dll! DllUnregisterServer - 0x00007FF9F9B86783, module offset(base): 0x46783(0x7ff9f9b40000)
StackTrace01=C:\Program Files\Screenovate\BluePhone\SpeechClient.dll! DllUnregisterServer - 0x00007FF9F9B8744E, module offset(base): 0x4744e(0x7ff9f9b40000)
StackTrace02=C:\Program Files\Screenovate\BluePhone\SpeechClient.dll! DllUnregisterServer - 0x00007FF9F9B88A95, module offset(base): 0x48a95(0x7ff9f9b40000)
StackTrace03=C:\Program Files\Screenovate\BluePhone\SpeechClient.dll! DllUnregisterServer - 0x00007FF9F9B87DD9, module offset(base): 0x47dd9(0x7ff9f9b40000)
StackTrace04=C:\Program Files\Screenovate\BluePhone\SpeechClient.dll! DllUnregisterServer - 0x00007FF9F9B83A8D, module offset(base): 0x43a8d(0x7ff9f9b40000)
StackTrace05=C:\Program Files\Screenovate\BluePhone\SpeechClient.dll! DllUnregisterServer - 0x00007FF9F9B831C8, module offset(base): 0x431c8(0x7ff9f9b40000)
StackTrace06=C:\Program Files\Screenovate\BluePhone\SpeechClient.dll! DllUnregisterServer - 0x00007FF9F9B718DA, module offset(base): 0x318da(0x7ff9f9b40000)
StackTrace07=C:\Program Files\Screenovate\BluePhone\SpeechClient.dll! DllUnregisterServer - 0x00007FF9F9BAF087, module offset(base): 0x6f087(0x7ff9f9b40000)
StackTrace08=C:\Program Files\Screenovate\BluePhone\SpeechClient.dll! DllUnregisterServer - 0x00007FF9F9BAEC4D, module offset(base): 0x6ec4d(0x7ff9f9b40000)

**Comment by kneptune** [comment]
Anyone have any idea as to how to fix this? I am pretty certain that I am using the correct subscription and application ID's.

**Comment by kngrace** [comment]
@jabels  I have encountered same/similar error - also using remote desktop into my dev machine. Did you find a fix or does anyone else have a suggestion?

--- Error received by OnConversationErrorHandler() ---
Error code: -2147023728
Error text: Transport error

**Comment by v-yuwaje** [comment]
Working fine when tested with sample application ,also in the comments they have mentioned that this seems to be working some time and giving error some time.
Have got similar error when have not provided subcscription key, so the requestor may have not provided key or may have provided wrong key.
Also reported issue is for 1.0.0.2 and now the nuget have latest 1.0.0.3 which seems to have resolved the issue.

**Comment by priyaravi20** [comment]
Closing as per last comment.

**Comment by CrimsonArc** [comment]
@v-yuwaje Funny, we are all programmers, do you really think we all not set the key or set a wrong key? This is not about key, not about the package. I'm using REST APIs, not the package, and have this issue.

**Comment by kngrace** [comment]
@priyaravi20 @v-yuwaje I have determined the source of my issue and have a suggested update to be made to the SDK.

Summary: I was receiving the "Transport Error" message. I often connect remotely to my developer machine and most of my computer's Local Resources are shared by default. It hadn't occurred to me that my microphone wouldn't also be shared even if my speakers were. Once I reconfigured my remote desktop settings to allow for my local machine's microphone to be made available, I no longer encountered an error and everything worked perfectly.

Repro: Remote desktop connection into another machine running this build and attempt to "Use Microphone" input without first sharing local microphone in remote desktop settings. Alternatively, disable all of your recording devices on your local machine and don't bother with remote desktop because the same error will occur when you attempt to "Use Microphone" input.

Suggested Fix: Create an error check/message that detects if no recording devices are available to use and outputs an error message suggestive of this problem rather than a generic "Transport Error" message. This may save the time of future developers trying to troubleshoot a simple problem.

![remote desktop audio recording](https://cloud.githubusercontent.com/assets/5940633/24013093/8e77093e-0a3d-11e7-8fba-22d22ddb8e42.png)

**Comment by TrungNguyen1909** [comment]
Funny error. It only works on my computer. All of my friends' Windows 10 Laptop get stopped working or login failed. weird error.

**Comment by MeQT** [comment]
This error ist so weird. the microphonefunction is working and not working on the same time on the same hardware, same os, same microphone and same drivers. but its always working on the one setup and never working on the other one. is there really no solution for this? 1.0.0.3 did not fix this unfortunaly.

**Comment by bryanjhogan** [comment]
What key are people using? 

I am trying with the access key of my Azure Bing Speech API and getting the login errors described above. 

I opened another issue see - https://github.com/Azure-Samples/Cognitive-Speech-STT-Windows/issues/25

![image](https://cloud.githubusercontent.com/assets/5768871/26258372/789b055c-3c92-11e7-9361-1289532a5cb4.png)
