### ISSUE TITLE
Cannot enroll more than one phrase at a time.

### ISSUE THREAD

**Issue by prateek03jan** [Microsoft/Cognitive-Speech-STT-Windows#15]
We are asked to enroll three voice samples for a single profile id.But after enrolling first voice sample, I am unable to add another two samples.

I am getting invalid phrase exception.

Please help me out.

**Comment by jasonvomsft** [comment]
@prateek03jan this sounds like an issue with Text-to-speech and not speech-to-text.  Can you add feedback to https://github.com/Microsoft/Cognitive-Speech-TTS instead?  Closing out for now.
