### ISSUE TITLE
How to get the required keys

### ISSUE THREAD

**Issue by FraukeN** [Microsoft/Cognitive-Speech-STT-Windows#19]
According to the instructions, I need three keys: my LUIS App ID and Subscription ID plus a Speech API subscription key.

I have created a LUIS account, but the only key that offers me is a Programmatic API Key, which is possibly what the instructions mean by the Speech API subscription key. I can see no obvious way of getting the others. 

This is my first foray into MS cognitive services and I just want to get this sample running to get a feel for the speech recognition API. I've never worked with LUIS before.

Where can I find those keys?

**Comment by v-yuwaje** [comment]
You can get information on how to get started and getting keys by visiting below link:
https://msdn.microsoft.com/en-US/library/mt712546.aspx

**Comment by priyaravi20** [comment]
Hi - You can get subscription keys separately for LUIS and Bing Speech from your azure portal and use them in the speech recognition API. AppID is what you use for your app and not generated from azure portal.
