### ISSUE TITLE
RecognitionStatus "611" is not defined  in RecognitionStatus enum in SpeechClient.dll

### ISSUE THREAD

**Issue by margaretmz** [Microsoft/Cognitive-Speech-STT-Windows#2]
_From @abuzany on April 22, 2016 17:23_

When I sent an a audio file I get "611" in PhraseResponse.RecognitionStatus in "OnDataDictationResponseReceivedHandler"  but that status is  not  defined in n RecognitionStatus enum

_Copied from original issue: Microsoft/ProjectOxford-ClientSDK#57_

**Comment by Sukshender** [comment]
Hi Margaret,

Could you please confirm if the error for "611" is fixed? Did you reopen the issue for SpeechClient.dll crashing problem?

Thanks,
SPS
