### ISSUE TITLE
Unable to integrate SpeechClient.dll with SharePoint as the assembly is not strong named

### ISSUE THREAD

**Issue by margaretmz** [Microsoft/Cognitive-Speech-STT-Windows#3]
_From @parijat1209 on April 14, 2016 9:50_

I need SpeechClient.dll to be strong named so that I can reference it in SharePoint project. Can you strong name the assemblies?

Thank You.

_Copied from original issue: Microsoft/ProjectOxford-ClientSDK#51_

**Comment by priyaravi20** [comment]
Currently the dll is windows signed. We will add it to list of asks for a future version.
