### ISSUE TITLE
a procedure imported by 'SpeachClient.dll' could not be loaded, on Windows 7

### ISSUE THREAD

**Issue by margaretmz** [Microsoft/Cognitive-Speech-STT-Windows#4]
_From @skalinkin on April 29, 2016 15:10_

I have build small app, it works on my box (Windows 10) I have copied Debug folder to my laptop for demo and got error above. see my project here https://github.com/skalinkin/PlayingWithSpeachToText
I have used nuget package but looks like missing some dependency

_Copied from original issue: Microsoft/ProjectOxford-ClientSDK#60_

**Comment by margaretmz** [comment]
_From @bennettl on May 13, 2016 8:7_

Having the same issue, is the C# SDK not compatible with Windows 7?

**Comment by margaretmz** [comment]
_From @skalinkin on May 13, 2016 11:38_

What I figured out is Windows 7 is not supported.

**Comment by jasonvomsft** [comment]
Windows 7 is not currently a supported platform.  The Windows Speech library has a hard dependency on the Windows 8 network stack.

I suggest using the HTTP REST API, or upgrade your Windows machine.

**Comment by YYurtcan** [comment]
How to use HTTP REST API?
