### ISSUE TITLE
How to increase Intial silence timeout

### ISSUE THREAD

**Issue by margaretmz** [Microsoft/Cognitive-Speech-STT-Windows#5]
_From @Jagadeesh-Govindaraj on June 13, 2016 9:46_

how can i incrase intial silence timeout in using speechreconizationservice factory

i did not see any property on this?

_Copied from original issue: Microsoft/ProjectOxford-ClientSDK#76_

**Comment by margaretmz** [comment]
_From @Jagadeesh-Govindaraj on June 13, 2016 9:47_

Speechtotext Windows api

**Comment by jasonvomsft** [comment]
@Jagadeesh-Govindaraj , the initial silence timeout is mandated by the service.  Can you explain your scenario a bit more as to why you need to increase this time?

**Comment by Milesbs** [comment]
up ! Is there a fix to that ? can we change the initial silence timeout to be continuous instead of limited to 15s ?

**Comment by priyaravi20** [comment]
silence timeouts are configured in service and cannot be sent from client. For a more continuous experience you can try using the Long mode.
