### ISSUE TITLE
error CS1061: 'DataRecognitionClient' does not contain a definition for 'WaitForFinalResponse' and no extension method 'WaitForFinalResponse'

### ISSUE THREAD

**Issue by margaretmz** [Microsoft/Cognitive-Speech-STT-Windows#6]
_From @kbpachauri on June 29, 2016 18:2_

I am trying to call WaitForFinalResponse, but getting error, According to sdk documentation, this method is supported (https://staging.www.projectoxford.ai/Files/Doc/Speech/Windows/html/ff4169e5-6142-558a-92af-48618f592f39.htm)
this.dataClient.WaitForFinalResponse();
kindly help. Thanks

_Copied from original issue: Microsoft/ProjectOxford-ClientSDK#82_

**Comment by jasonvomsft** [comment]
The WaitForFinalResponse API was deprecated in the October 2015 release.  We will update the documentation.
